import React from 'react'

export default function AboutUs() {
  return (
    <main className='text-black bg-white dark:bg-black dark:text-white mt-20 mx-6 p-4 shadow-md rounded-xl shadow-neutral-700 dark:shadow-neutral-100'>
      <h1>About Us</h1>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, perspiciatis sapiente? Nam velit sunt at odio delectus, quisquam doloremque soluta, officiis eligendi nihil corporis nostrum dolor quod laboriosam voluptatibus iusto vitae. Magni earum provident possimus quidem quae, labore deserunt, voluptate asperiores totam natus nam voluptates quo at, voluptatum architecto quaerat perferendis ullam minima tenetur perspiciatis facilis tempore a nulla neque. Repellendus officiis, perspiciatis optio velit itaque ex a sint culpa perferendis ducimus, ad recusandae ea dolore inventore repudiandae laborum explicabo corrupti impedit. Ipsum itaque dolorem fugit aliquam deserunt, cum quaerat impedit dolore illum dolores obcaecati? Sunt dolores laudantium quasi. At omnis blanditiis amet eligendi quae iusto vel perferendis architecto aut perspiciatis enim minima iure inventore quod expedita praesentium eveniet aliquid ratione, ipsum quidem hic aperiam? Amet, temporibus. Eum esse, mollitia nemo eaque molestiae, sed corrupti itaque porro tempora sint optio voluptatibus velit quas quis. Debitis, nihil, blanditiis suscipit itaque adipisci assumenda nostrum, nobis nisi hic saepe laudantium rerum ut quibusdam ducimus dicta eligendi sit impedit nulla corrupti consequatur praesentium ratione deserunt magnam? Minus dolorem sunt inventore ab, fuga placeat quas aperiam accusantium facilis cupiditate, libero ipsum iure consectetur similique quasi alias? Animi error incidunt nostrum amet unde inventore culpa totam dolores in ea minima deleniti voluptatibus aliquid, non accusamus nesciunt explicabo similique. Iure cum ex nobis? Blanditiis beatae, atque qui saepe velit doloribus perspiciatis non sed eveniet, modi aspernatur fugiat eaque amet quasi. Non voluptates adipisci iste soluta aliquam ipsum provident minus delectus velit veniam optio odit quasi debitis, laboriosam dolorum at saepe sunt eaque? Consequatur exercitationem sequi vero minima nam hic, nemo error! Pariatur dolores voluptatem tenetur accusamus vel. Quisquam alias omnis, illo voluptas nulla rerum ab consectetur iste illum dignissimos. Accusamus, pariatur atque quidem eius odio doloremque obcaecati aliquam similique quia, sint ut quo, molestias nemo! Sit, explicabo.
    </main>
  )
}
